Repository burnash/gspread, pull requests merged in 2021-07, with the labels that each got.

#891 Improvement: Allow users to provide a custom credentials file to oauth()
  docs/oauth2.rst
  gspread/auth.py
Labels: Improvement

#895 Improvement - allow creation of spreadsheets in shared drives
  gspread/client.py
Labels: Feature Request

#898 Fix client.copy copy_permission argument compare
  gspread/client.py
Labels: Bug

#897 add batch_clear method to worksheet
  docs/user-guide.rst
  gspread/models.py
  gspread/urls.py
  tests/test.py
Labels: Feature Request

#899 find method return none
  docs/user-guide.rst
  gspread/models.py
  tests/test.py
Labels: Improvement
