Repository burnash/gspread, pull requests merged in 2021-12, with the labels that each got.

#962 Codespell skip docs build folder
  HISTORY.rst
  tox.ini
Labels: Bug

#964 Update contributing guidelines
  .github/CONTRIBUTING.md
Labels: Docs

#967 Improvement/add oauth from dict
  docs/oauth2.rst
  gspread/__init__.py
  gspread/auth.py
Labels: Feature Request

#972 Аutomatic conversion of a cell letter to uppercase
  gspread/utils.py
Labels: Bug

#975 Fix documentation about oauth
  docs/oauth2.rst
Labels: Bug, Docs
