Repository burnash/gspread, pull requests merged in 2021-09, with the labels that each got.

#918 Upgrade to modern Python syntax
  .github/workflows/lint_python.yml
  docs/conf.py
  gspread/__init__.py
  gspread/auth.py
  gspread/cell.py
  gspread/client.py
  gspread/exceptions.py
  gspread/spreadsheet.py
  gspread/urls.py
  gspread/utils.py
  gspread/worksheet.py
  tests/cell_test.py
  tests/client_test.py
  tests/spreadsheet_test.py
  tests/test.py
  tests/utils_test.py
  tests/worksheet_test.py
Labels: Improvement

#921 Bugfix - remove wrong argument in `batch_update` docstring
  gspread/worksheet.py
Labels: Bug, Docs

#922 Improvement - Add `Worksheet.index` property
  gspread/worksheet.py
Labels: Feature Request

#930 Feature/improve tox file
  .github/workflows/lint_python.yml
  README.md
  docs/index.rst
  setup.py
  test-requirements.txt
  tox.ini
Labels: Improvement
