Repository burnash/gspread, pull requests merged in 2021-08, with the labels that each got.

#902 Bugfix - in numericise do to overwirte original value
  gspread/utils.py
Labels: Bug

#869 GitHub Action to lint Python code
  .github/workflows/lint_python.yml
  HISTORY.rst
  test-requirements.txt
  tests/cell_test.py
  tests/client_test.py
  tests/test.py
  tox.ini
Labels: Improvement, help wanted

#915 Improvement/lint code
  .github/workflows/lint_python.yml
  docs/conf.py
  gspread/__init__.py
  gspread/auth.py
  gspread/client.py
  gspread/exceptions.py
  gspread/urls.py
  gspread/utils.py
  gspread/worksheet.py
  setup.py
  tests/cell_test.py
  tests/client_test.py
  tests/test.py
Labels: Improvement

#916 lint_python.yml: Try 'tox -e py' to test current Python
  .github/workflows/lint_python.yml
Labels: Improvement
