Repository burnash/gspread, pull requests merged in 2023-10, with the labels that each got.

#1312 Fix warning message for `worksheet.update` method
  gspread/worksheet.py
Labels: Improvement, Docs

#1305 Add `maintain_size` to keep asked for size in `get`, `get_values`
  README.md
  gspread/utils.py
  gspread/worksheet.py
  tests/cassettes/WorksheetTest.test_get_values_and_maintain_size.json
  tests/cassettes/WorksheetTest.test_update_acell.json
  tests/utils_test.py
  tests/worksheet_test.py
Labels: Feature Request, Improvement

#1297 feature/readme migration v6
  README.md
Labels: Docs
